LearnRails4/Chapter3/sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'passwords_resets/new'

  get 'passwords_resets/edit'

  get 'sessions/new'

  root 				'static_pages#home'
  get  'help'  	 =>	'static_pages#help'
  get  'about'   =>	'static_pages#about'
  get  'contact' =>	'static_pages#contact'
  get  'signup'  => 'users#new'
  get  'login'	 => 'sessions#new'
  post 'login'	 => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update ]
  resources :microposts,      only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

LearnRails4/Chapter3/sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<a href="#" id="logo">sample app</a>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/">Home</a> </li>
				<li><a href="/help">Help</a> </li>
				<% if logged_in? %>
					<li><%= link_to "User", users_path  %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: "delete"  %>
							</li>
						</ul>
					</li>
				<% else %>				
					<li><%= link_to "Log in", login_path  %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

LearnRails4/Chapter3/sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header"%>
	<div class="container">
		<% flash.each do |message_type, message|  %>
			<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
		<% end %>
		<%= yield %>	
	</div>
	<%= render "layouts/footer"%>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>